custom_admin_syssetting:
    resource: "@CustomAdminBundle/Resources/config/routing/systemsetting.yml"
    prefix:   /syssetting

custom_admin_homepage:
    path:     /
    defaults: { _controller: CustomAdminBundle:Default:index }

custom_admin_test:
    path:     /test
    defaults: { _controller: CustomAdminBundle:Default:test }